### ISSUE TITLE
feat: Deployment GUI for federation and site provision and management

### ISSUE THREAD

**Issue by LaynePeng** [FederatedAI/FATE-Community#45]
**Describe the solution you'd like**
Currently, we have deployment approaches like KubeFATE, and Ansible for the FATE cluster on one site. But we lack the federation level provision and management solution.  The goal is to orchestrate the provisioning of multiple sites to form a globally secure and well-governed a federation.

Furthermore, current deployment solutions (including KubeFATE and Ansible) are CLI-based, which is still an overstretched requirement for personnel with only infrastructure knowledge. An easy-to-use GUI deployment solution is needed.

**Describe alternatives you've considered**
A Federated Lifecycle Manager (federation level lifecycle management system) is needed. The system should be easy to use for large-scale FATE cluster provisioning and management.

We can create a new repo for the Federated Lifecycle Manager (FedLCM) for the development of this feature.

**Comment by dylan-fan** [comment]
+LGTM

**Comment by jarviszeng-zjc** [comment]
LGTM

**Comment by excellent-lixl** [comment]
LGTM

**Comment by hainingzhang** [comment]
+1 LGTM

**Comment by snowzjx** [comment]
LGTM

**Comment by hainingzhang** [comment]
This feature request and contribution to FATE has been approved. A new repo will be created to host code for it.
