### ISSUE TITLE
FATE-Builder： A release packing tool for FATE

### ISSUE THREAD

**Issue by dylan-fan** [FederatedAI/FATE-Community#46]
What is FATE-Builder?
1. FATE has many release packages, such as Standalone, AllinOne, AnsibleFATE, etc. Before FATE 1.8, these packages were built manually. It requires the maintainer to use multiple scripts to build each package.
2. On FATE 1.8, all release packages were built automatically by FATE-Builder with just one command. And it is CI friendly, it can be integrated into GitHub CI for automatic releasing.

Why use a separate repository?
1. FATE-Builder includes some templates for generating packages, e.g. AnsibleFATE. Normal users does not need these templates.
2. FATE-Builder does not require a specific FATE version. Currently, it supports FATE 1.7+ and has been fully tested on FATE 1.8.
3. FATE-Builder does not use any script from FATE repository. It can clone, pull, build FATE and all submodules (eggroll, fateflow and fateboard), so it can run independently.

We can create a new repo for FATE-Bulder for the development of this feature.

**Comment by dylan-fan** [comment]
+ LGTM

**Comment by snowzjx** [comment]
LGTM

**Comment by LaynePeng** [comment]
LGTM

**Comment by excellent-lixl** [comment]
LGTM

**Comment by hainingzhang** [comment]
LGTM

**Comment by jarviszeng-zjc** [comment]
LGTM
It may also be possible to support specifying the actual algorithm components required for execution, thus building fewer dependency packages on demand and reducing deployment package size.

**Comment by hainingzhang** [comment]
This new feature has been approved. A new repo will be created to host the code for the build tool.
