### ISSUE TITLE
Voting on ByteDance as an organization member

### ISSUE THREAD

**Issue by kelley1069** [FederatedAI/FATE-Community#73]
ByteDance has passed the preliminary review and completed the assessment. TSC board members are requested to vote based on the assessment result, either "agree" or "disagree." 
If more than half of the votes are favored, ByteDance will officially become a FATE community organization member.

**Comment by snowzjx** [comment]
agree from Clustar

**Comment by QiangYang12** [comment]
agree from WeBank

**Comment by hainingzhang** [comment]
agree

**Comment by sunxzycn** [comment]
From ICBC
Agree
